services:
  # Backend API
  - type: web
    name: live-polling-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/challasumanth64/Online-Voting-System
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: 4000
      - key: ORIGIN
        value: https://live-polling-frontend.onrender.com
      - key: TEACHER_SECRET
        value: changeme

  # Frontend
  - type: web
    name: live-polling-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    repo: https://github.com/challasumanth64/Online-Voting-System
    region: oregon
    plan: free
    envVars:
      - key: VITE_SERVER_URL
        value: https://live-polling-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html