services:
  # Backend API
  - type: web
    name: live-polling-backend
    env: node
    buildCommand: npm install --prefix server
    startCommand: npm start --prefix server
    repo: https://github.com/challasumanth64/Online-Voting-System
    region: oregon
    plan: free
    # Environment variables should be set in the Render dashboard:
    # PORT: 4000 (automatically set by Render, but defined here for clarity)
    # ORIGIN: https://your-frontend-url.onrender.com
    # TEACHER_SECRET: your-secret-key-change-in-dashboard

  # Frontend
  - type: web
    name: live-polling-frontend
    env: static
    buildCommand: npm install --prefix client && npm run build --prefix client
    staticPublishPath: ./client/dist
    repo: https://github.com/challasumanth64/Online-Voting-System
    region: oregon
    plan: free
    # Environment variables should be set in the Render dashboard:
    # VITE_SERVER_URL: https://your-backend-url.onrender.com